#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p1_collatz       # job name
#SBATCH -o p1_collatz.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p gpu              # queue name
#SBATCH -t 00:02:00         # expected maximum runtime (hh:mm:ss)

date

./collatz 1000000
./collatz 10000000
./collatz 100000000

date

